language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

before_script: travis_retry composer install --no-interaction --prefer-source

script:
  - travis_wait bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi;'
  - travis_wait bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi;'
